[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Seth Gower <sethzerish@gmail.com>", "Scoder12"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aocf = "0.1.8"
getopts = "0.2.0"
